<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="../../Assets/NTSD/Scripts/DatParser/Runtime/Utils/LoganNumericDecoder.cs" Link="LoganNumericDecoder.cs" />
  </ItemGroup>
</Project>
