type Json = Record<string, unknown>;
import { mergePreview, spritePlacement } from "./project-client.js";
type Frame = Json & { frameId: number };
type TickEntity = Json & { frame: number; oid: number; x: number; y: number; z: number };
type NativeTick = Json & { entities: TickEntity[]; cameraX: number };
interface ProjectState { sessionId: string; revision: string | number; name: string; dirty: boolean; frames: Frame[]; ranges: Json[]; nativeTicks: NativeTick[]; assets: Map<string, string>; fieldIds: Map<string, string>; }

const select = <T extends Element>(id: string): T | null => document.querySelector<T>(`#${id}`);
const status = select<HTMLElement>("server-status"), diagnostics = select<HTMLElement>("diagnostics"), canvas = select<HTMLCanvasElement>("sprite-canvas");
const objectSelect = select<HTMLSelectElement>("object-select"), frameSelect = select<HTMLSelectElement>("frame-select"), seek = select<HTMLInputElement>("timeline-seek"), loop = select<HTMLInputElement>("loop-enabled"), playButton = select<HTMLButtonElement>("play-toggle"), fields = select<HTMLElement>("frame-fields");
let project: ProjectState | undefined, tickIndex = 0, playing = false, timer: number | undefined, stateToken = "", tokenHeader = "x-dat-skill-flow-token", renderedFrameId: number | undefined, dirtyFieldKey: string | undefined;
const images = new Map<string, HTMLImageElement>();
const record = (value: unknown): Json => value !== null && typeof value === "object" ? value as Json : {};
const list = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
const text = (value: unknown): string => typeof value === "string" ? value : "";
const number = (value: unknown, fallback = 0): number => typeof value === "number" && Number.isFinite(value) ? value : fallback;

async function request(path: string, init?: RequestInit, stateChanging = false): Promise<Json> {
    const headers: Record<string, string> = { Accept: "application/json", ...(init?.headers as Record<string, string> ?? {}) };
    if (stateChanging) { headers["Content-Type"] = "application/json"; if (stateToken) headers[tokenHeader] = stateToken; }
    const response = await fetch(path, { ...init, headers }); const body = record(await response.json());
    if (!response.ok) throw new Error(text(body.message) || `${response.status} ${path}`); return body;
}
function normalize(payload: Json): ProjectState {
    const data = record(payload.data), session = record(data.document ?? data.session ?? data.project ?? data), projection = record(session.projection ?? data.projection);
    const preview = record(session.nativePreview ?? session.preview ?? session.trace ?? data.nativePreview ?? data.preview ?? data.trace);
    const frames = list(projection.frames ?? session.frames).map((value, index) => ({ ...record(value), frameId: number(record(value).frameId ?? record(value).id, index) }));
    const assets = new Map<string, string>();
    for (const value of list(session.assets ?? session.spriteAssets ?? data.assets ?? data.spriteAssets)) { const asset = record(value); const id = text(asset.assetId ?? asset.id); if (id) assets.set(text(asset.file), id); }
    const fallbackAsset = text(session.assetId ?? data.assetId); if (fallbackAsset) assets.set("", fallbackAsset);
    const fieldIds = new Map<string, string>();
    for (const value of list(session.fields ?? data.fields)) { const field = record(value), id = text(field.fieldId ?? field.id); if (id) fieldIds.set(`${number(field.frameId)}:${text(field.key)}`, id); }
    const ticks = list(preview.ticks ?? preview.nativeTicks ?? session.ticks).map((value) => { const raw = record(value); return { ...raw, cameraX: number(raw.camera_x ?? raw.cameraX), entities: list(raw.entities).map((entity) => { const item = record(entity); return { ...item, oid: number(item.oid), frame: number(item.frame), x: number(item.x), y: number(item.y), z: number(item.z) }; }) }; });
    return { sessionId: text(session.sessionId ?? data.sessionId), revision: (session.revision ?? data.revision ?? "-") as string | number, name: text(session.name ?? data.name ?? "Project"), dirty: session.dirty === true || data.dirty === true, frames, ranges: list(projection.spriteRanges ?? session.spriteRanges ?? data.spriteRanges).map(record), nativeTicks: ticks, assets, fieldIds };
}
function currentFrame(): Frame | undefined { const primary = project?.nativeTicks[tickIndex]?.entities.find((entity) => entity.oid === 2) ?? project?.nativeTicks[tickIndex]?.entities[0]; return project?.frames.find((frame) => frame.frameId === primary?.frame) ?? project?.frames[0]; }
function update(): void { const frame = currentFrame(), count = project?.nativeTicks.length ?? 0; select<HTMLElement>("tick-readout")!.textContent = String(tickIndex); select<HTMLElement>("frame-readout")!.textContent = frame ? String(frame.frameId) : "-"; select<HTMLElement>("time-readout")!.textContent = `${tickIndex * 33} ms`; if (frameSelect && frame) frameSelect.value = String(frame.frameId); if (renderedFrameId !== frame?.frameId) { renderedFrameId = frame?.frameId; renderFields(); } if (seek) { seek.max = String(Math.max(0, count - 1)); seek.value = String(tickIndex); } if (playButton) { playButton.textContent = playing ? "Pause" : "Play"; playButton.ariaPressed = String(playing); } draw(); }
function loadImage(assetId: string): HTMLImageElement { let image = images.get(assetId); if (!image) { image = new Image(); image.src = `/api/assets/${encodeURIComponent(assetId)}`; image.onload = update; images.set(assetId, image); } return image; }
function draw(): void { const context = canvas?.getContext("2d"), tick = project?.nativeTicks[tickIndex]; if (!canvas || !context) return; context.clearRect(0, 0, canvas.width, canvas.height); if (!tick || !project) { context.fillText("No native preview ticks returned.", 20, 30); return; } for (const entity of tick.entities) { const isLoadedObject = entity.oid === 2; const frame = isLoadedObject ? project.frames.find((candidate) => candidate.frameId === entity.frame) : undefined, pic = number(frame?.pic ?? entity.pic, 999); const range = isLoadedObject ? project.ranges.find((candidate) => pic >= number(candidate.frameLo ?? candidate.frame_lo) && pic <= number(candidate.frameHi ?? candidate.frame_hi, -1)) : undefined; const w = number(range?.w, 24), h = number(range?.h, 24); const placement = spritePlacement({ xInt: number(entity.xInt ?? entity.x), yInt: number(entity.yInt ?? entity.y), zInt: number(entity.zInt ?? entity.z), renderOffsetX: number(entity.renderOffsetX), cameraX: tick.cameraX, centerX: number(frame?.centerx), centerY: number(frame?.centery), width: w, facing: number(entity.facing) }); const assetId = range === undefined ? undefined : (text(range.assetId) || project.assets.get(text(range.file)) || project.assets.get("")); if (!range || !assetId || pic === 999) { context.strokeStyle = "#f4b34b"; context.strokeRect(placement.x, placement.y, 24, 24); context.fillText(`OID ${entity.oid} F${entity.frame}`, placement.x, placement.y - 6); continue; } const cols = number(range.row); if (w <= 0 || h <= 0 || cols <= 0) continue; const local = pic - number(range.frameLo ?? range.frame_lo), image = loadImage(assetId); context.save(); if (placement.mirror) { context.translate(placement.x + w, placement.y); context.scale(-1, 1); context.drawImage(image, (local % cols) * (w + 1), Math.floor(local / cols) * (h + 1), w, h, 0, 0, w, h); } else context.drawImage(image, (local % cols) * (w + 1), Math.floor(local / cols) * (h + 1), w, h, placement.x, placement.y, w, h); context.restore(); } }
function render(): void { if (!project) return; frameSelect?.replaceChildren(...project.frames.map((frame) => { const option = document.createElement("option"); option.value = String(frame.frameId); option.textContent = `#${frame.frameId} pic ${number(frame.pic)}`; return option; })); renderFields(); update(); }
function renderFields(): void { fields?.replaceChildren(); dirtyFieldKey = undefined; const frame = currentFrame(); if (!frame || !fields) return; for (const [key, value] of Object.entries(frame)) { if (typeof value !== "number" || key === "frameId") continue; const label = document.createElement("label"), input = document.createElement("input"); label.textContent = key; input.name = key; input.type = "number"; input.value = String(value); input.addEventListener("input", () => { dirtyFieldKey = key; }); label.append(input); fields.append(label); } }
async function preview(startFrame: number): Promise<void> { if (!project) return; const response = await request("/api/project/preview", { method: "POST", body: JSON.stringify({ sessionId: project.sessionId, expectedRevision: project.revision, startFrame, ticks: 180 }) }, true); const partial = normalize(response); project = mergePreview(project, partial.revision, partial.nativeTicks) as ProjectState; tickIndex = 0; render(); }
function step(): void { const last = Math.max(0, (project?.nativeTicks.length ?? 1) - 1); tickIndex = tickIndex >= last ? (loop?.checked ? 0 : last) : tickIndex + 1; update(); }
function schedule(): void { if (!playing || timer !== undefined) return; timer = window.setTimeout(() => { timer = undefined; step(); schedule(); }, 33); }
async function open(objectKey: string, oid: number): Promise<void> { const response = await request("/api/project/open", { method: "POST", body: JSON.stringify({ objectKey }) }, true); project = normalize(response); tickIndex = 0; status!.textContent = `Loaded ${project.name} / OID ${oid}`; select<HTMLElement>("session-name")!.textContent = project.name; select<HTMLElement>("revision-readout")!.textContent = `revision ${project.revision}`; select<HTMLElement>("dirty-readout")!.textContent = project.dirty ? "dirty" : "clean"; render(); }
async function start(): Promise<void> { try { const bootstrap = record((await request("/api/bootstrap")).data), security = record(bootstrap.security); stateToken = text(security.token ?? bootstrap.stateToken ?? bootstrap.token); tokenHeader = text(security.tokenHeader ?? bootstrap.tokenHeader) || tokenHeader; const listing = record((await request("/api/project")).data); const choices = list(listing.objects ?? listing.entries); objectSelect?.replaceChildren(...choices.map((value) => { const item = record(value), oid = number(item.oid), objectKey = text(item.objectKey); const option = document.createElement("option"); option.value = objectKey; option.dataset.oid = String(oid); option.textContent = `OID ${oid} ${text(item.name)}`; option.selected = oid === 2; return option; })); const selected = objectSelect?.selectedOptions[0]; await open(objectSelect?.value || "", number(selected?.dataset.oid, 2)); } catch (error) { status!.textContent = "Project unavailable"; diagnostics!.textContent = error instanceof Error ? error.message : "Project load failed."; } }
objectSelect?.addEventListener("change", () => { const option = objectSelect.selectedOptions[0]; void open(objectSelect.value, number(option?.dataset.oid)); }); frameSelect?.addEventListener("change", () => void preview(Number(frameSelect.value))); seek?.addEventListener("input", () => { tickIndex = Number(seek.value); update(); }); playButton?.addEventListener("click", () => { playing = !playing; update(); schedule(); }); select("step-once")?.addEventListener("click", step); select("reset-timeline")?.addEventListener("click", () => { tickIndex = 0; update(); });
select<HTMLFormElement>("frame-editor")?.addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget), frame = currentFrame(), key = dirtyFieldKey; if (!key || !project || !frame) return; const fieldId = project.fieldIds.get(`${frame.frameId}:${key}`); if (!fieldId) { diagnostics!.textContent = `No editable field id for ${key}.`; return; } void request("/api/project/edit", { method: "POST", body: JSON.stringify({ sessionId: project.sessionId, fieldId, value: Number(form.get(key)), expectedRevision: project.revision }) }, true).then((response) => { project = normalize(response); select<HTMLElement>("revision-readout")!.textContent = `revision ${project.revision}`; select<HTMLElement>("dirty-readout")!.textContent = project.dirty ? "dirty" : "clean"; return preview(frame.frameId); }).catch((error) => diagnostics!.textContent = String(error)); });
select("save-project")?.addEventListener("click", () => project && void request("/api/project/save", { method: "POST", body: JSON.stringify({ sessionId: project.sessionId, expectedRevision: project.revision }) }, true).then((response) => { const saved = normalize(response); if (project) project = { ...project, revision: saved.revision, dirty: false }; select<HTMLElement>("revision-readout")!.textContent = `revision ${project?.revision ?? "-"}`; select<HTMLElement>("dirty-readout")!.textContent = "clean"; diagnostics!.textContent = "Saved."; }).catch((error) => diagnostics!.textContent = String(error)));
for (const key of ["a", "d", "j", "Fj", "Fa", "Da", "Ua", "ja", "Dj", "Uj"]) select(`hit-${key.toLowerCase()}`)?.addEventListener("click", () => { const target = number(currentFrame()?.[`hit_${key}`]); if (target >= 0) void preview(target); });
void start();
